server:
  port: 6064
---
spring:
  r2dbc:
    url: 'r2dbc:postgresql://localhost:6301/url_shortener_reactive'
    username: root
    password: 12345678
  liquibase:
    url: 'jdbc:postgresql://localhost:6301/url_shortener_reactive'
    user: root
    password: 12345678
---
url-shortener:
  base-url: http://localhost:6064
