---
server:
  port: 6060
---
spring:
  data:
    redis:
      port: 6300
---
routes.application.uri: http://localhost:6061
---
logging:
  level:
    com:
      matevskial:
        systemdesignplayground: DEBUG
---
