---
spring:
  application:
    name: system-design-playground-api-gateway
---
spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 70000
      routes:
        - id: application-rate-limited-configuration1
          uri: ${routes.application.uri}
          predicates:
            - Path=/application/api/v1/ratelimited/configuration1**
          filters:
            - StripPrefix=1
            - name: TokenBucketRateLimiter
              args:
                capacity: 3
                refillAmount: 2
                refillTimePeriod: 1
                refillTimeUnit: MINUTES
                kind: USING_LIBRARY
        - id: application-rate-limited-configuration2
          uri: ${routes.application.uri}
          predicates:
            - Path=/application/api/v1/ratelimited/configuration2**
          filters:
            - StripPrefix=1
            - name: TokenBucketRateLimiter
              args:
                capacity: 3
                refillAmount: 2
                refillTimePeriod: 1
                refillTimeUnit: MINUTES
                kind: CUSTOM
        - id: application-rate-limited-leakingbucket1
          uri: ${routes.application.uri}
          predicates:
            - Path=/application/api/v1/ratelimited/leakingbucket1**
          filters:
            - StripPrefix=1
            - name: LeakingBucketRateLimiter
              args:
                capacity: 10
                outflowRateInSeconds: 5
        - id: application
          uri: ${routes.application.uri}
          predicates:
            - Path=/application/**
          filters:
            - StripPrefix=1
---
