name: system-design-playground

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6300:6379"
  postgres:
    image: percona/percona-distribution-postgresql:16.8
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345678
    ports:
      - "6301:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
    ports:
      - "6302:80"
    restart: always

volumes:
  postgres_data:
